// DON'T EDIT *** generated by scaneo *** DON'T EDIT //

package model

import "database/sql"

func ScanArticle(r *sql.Row) (Article, error) {
	var s Article
	if err := r.Scan(
		&s.Title,
		&s.Body,
	); err != nil {
		return Article{}, err
	}
	return s, nil
}

func ScanArticles(rs *sql.Rows) ([]Article, error) {
	structs := make([]Article, 0, 16)
	var err error
	for rs.Next() {
		var s Article
		if err = rs.Scan(
			&s.Title,
			&s.Body,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

func ScanTimeline(r *sql.Row) (Timeline, error) {
	var s Timeline
	if err := r.Scan(
		&s.Title,
	); err != nil {
		return Timeline{}, err
	}
	return s, nil
}

func ScanTimelines(rs *sql.Rows) ([]Timeline, error) {
	structs := make([]Timeline, 0, 16)
	var err error
	for rs.Next() {
		var s Timeline
		if err = rs.Scan(
			&s.Title,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}
